# This is a basic workflow to help you get started with Actions

name: Update Gatsby Build

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
    - name: Trigger my downstream workflow
      run: |
        curl -XPOST -u "${{ secrets.PAT }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/jolbol1/jolbol1.github.io/actions/workflows/pages.yml/dispatches --data '{"ref": "main" }'
